package com.ril.bean;

public class Machine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine.machid
     *
     * @mbg.generated
     */
    private Long machid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine.noc
     *
     * @mbg.generated
     */
    private Integer noc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine.value
     *
     * @mbg.generated
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine.date
     *
     * @mbg.generated
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine.mode
     *
     * @mbg.generated
     */
    private Integer mode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine.machid
     *
     * @return the value of machine.machid
     *
     * @mbg.generated
     */
    public Long getMachid() {
        return machid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine.machid
     *
     * @param machid the value for machine.machid
     *
     * @mbg.generated
     */
    public void setMachid(Long machid) {
        this.machid = machid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine.name
     *
     * @return the value of machine.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine.name
     *
     * @param name the value for machine.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine.noc
     *
     * @return the value of machine.noc
     *
     * @mbg.generated
     */
    public Integer getNoc() {
        return noc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine.noc
     *
     * @param noc the value for machine.noc
     *
     * @mbg.generated
     */
    public void setNoc(Integer noc) {
        this.noc = noc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine.value
     *
     * @return the value of machine.value
     *
     * @mbg.generated
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine.value
     *
     * @param value the value for machine.value
     *
     * @mbg.generated
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine.date
     *
     * @return the value of machine.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine.date
     *
     * @param date the value for machine.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine.mode
     *
     * @return the value of machine.mode
     *
     * @mbg.generated
     */
    public Integer getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine.mode
     *
     * @param mode the value for machine.mode
     *
     * @mbg.generated
     */
    public void setMode(Integer mode) {
        this.mode = mode;
    }
}