package com.ril.bean;

import java.util.Date;

public class NOCRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nocrecord.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nocrecord.date
     *
     * @mbg.generated
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nocrecord.machid
     *
     * @mbg.generated
     */
    private Long machid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nocrecord.noc
     *
     * @mbg.generated
     */
    private Integer noc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nocrecord.value
     *
     * @mbg.generated
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nocrecord.recordtime
     *
     * @mbg.generated
     */
    private Date recordtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nocrecord.id
     *
     * @return the value of nocrecord.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nocrecord.id
     *
     * @param id the value for nocrecord.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nocrecord.date
     *
     * @return the value of nocrecord.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nocrecord.date
     *
     * @param date the value for nocrecord.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nocrecord.machid
     *
     * @return the value of nocrecord.machid
     *
     * @mbg.generated
     */
    public Long getMachid() {
        return machid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nocrecord.machid
     *
     * @param machid the value for nocrecord.machid
     *
     * @mbg.generated
     */
    public void setMachid(Long machid) {
        this.machid = machid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nocrecord.noc
     *
     * @return the value of nocrecord.noc
     *
     * @mbg.generated
     */
    public Integer getNoc() {
        return noc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nocrecord.noc
     *
     * @param noc the value for nocrecord.noc
     *
     * @mbg.generated
     */
    public void setNoc(Integer noc) {
        this.noc = noc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nocrecord.value
     *
     * @return the value of nocrecord.value
     *
     * @mbg.generated
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nocrecord.value
     *
     * @param value the value for nocrecord.value
     *
     * @mbg.generated
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nocrecord.recordtime
     *
     * @return the value of nocrecord.recordtime
     *
     * @mbg.generated
     */
    public Date getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nocrecord.recordtime
     *
     * @param recordtime the value for nocrecord.recordtime
     *
     * @mbg.generated
     */
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }
}