package com.ril.bean;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.machid
     *
     * @mbg.generated
     */
    private Long machid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.noc
     *
     * @mbg.generated
     */
    private String noc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.stocknumber
     *
     * @mbg.generated
     */
    private String stocknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.value
     *
     * @mbg.generated
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.date
     *
     * @mbg.generated
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.executionorder
     *
     * @mbg.generated
     */
    private Integer executionorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.id
     *
     * @return the value of task.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.id
     *
     * @param id the value for task.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.machid
     *
     * @return the value of task.machid
     *
     * @mbg.generated
     */
    public Long getMachid() {
        return machid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.machid
     *
     * @param machid the value for task.machid
     *
     * @mbg.generated
     */
    public void setMachid(Long machid) {
        this.machid = machid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.noc
     *
     * @return the value of task.noc
     *
     * @mbg.generated
     */
    public String getNoc() {
        return noc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.noc
     *
     * @param noc the value for task.noc
     *
     * @mbg.generated
     */
    public void setNoc(String noc) {
        this.noc = noc == null ? null : noc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.stocknumber
     *
     * @return the value of task.stocknumber
     *
     * @mbg.generated
     */
    public String getStocknumber() {
        return stocknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.stocknumber
     *
     * @param stocknumber the value for task.stocknumber
     *
     * @mbg.generated
     */
    public void setStocknumber(String stocknumber) {
        this.stocknumber = stocknumber == null ? null : stocknumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.value
     *
     * @return the value of task.value
     *
     * @mbg.generated
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.value
     *
     * @param value the value for task.value
     *
     * @mbg.generated
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.date
     *
     * @return the value of task.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.date
     *
     * @param date the value for task.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.executionorder
     *
     * @return the value of task.executionorder
     *
     * @mbg.generated
     */
    public Integer getExecutionorder() {
        return executionorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.executionorder
     *
     * @param executionorder the value for task.executionorder
     *
     * @mbg.generated
     */
    public void setExecutionorder(Integer executionorder) {
        this.executionorder = executionorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}