package com.ril.bean;

import java.util.Date;

public class TCPRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcprecord.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcprecord.machid
     *
     * @mbg.generated
     */
    private Long machid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcprecord.mode
     *
     * @mbg.generated
     */
    private Integer mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcprecord.noc
     *
     * @mbg.generated
     */
    private String noc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcprecord.stockNumber
     *
     * @mbg.generated
     */
    private String stocknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcprecord.count
     *
     * @mbg.generated
     */
    private Long count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcprecord.recordtime
     *
     * @mbg.generated
     */
    private Date recordtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcprecord.id
     *
     * @return the value of tcprecord.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcprecord.id
     *
     * @param id the value for tcprecord.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcprecord.machid
     *
     * @return the value of tcprecord.machid
     *
     * @mbg.generated
     */
    public Long getMachid() {
        return machid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcprecord.machid
     *
     * @param machid the value for tcprecord.machid
     *
     * @mbg.generated
     */
    public void setMachid(Long machid) {
        this.machid = machid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcprecord.mode
     *
     * @return the value of tcprecord.mode
     *
     * @mbg.generated
     */
    public Integer getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcprecord.mode
     *
     * @param mode the value for tcprecord.mode
     *
     * @mbg.generated
     */
    public void setMode(Integer mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcprecord.noc
     *
     * @return the value of tcprecord.noc
     *
     * @mbg.generated
     */
    public String getNoc() {
        return noc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcprecord.noc
     *
     * @param noc the value for tcprecord.noc
     *
     * @mbg.generated
     */
    public void setNoc(String noc) {
        this.noc = noc == null ? null : noc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcprecord.stockNumber
     *
     * @return the value of tcprecord.stockNumber
     *
     * @mbg.generated
     */
    public String getStocknumber() {
        return stocknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcprecord.stockNumber
     *
     * @param stocknumber the value for tcprecord.stockNumber
     *
     * @mbg.generated
     */
    public void setStocknumber(String stocknumber) {
        this.stocknumber = stocknumber == null ? null : stocknumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcprecord.count
     *
     * @return the value of tcprecord.count
     *
     * @mbg.generated
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcprecord.count
     *
     * @param count the value for tcprecord.count
     *
     * @mbg.generated
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcprecord.recordtime
     *
     * @return the value of tcprecord.recordtime
     *
     * @mbg.generated
     */
    public Date getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcprecord.recordtime
     *
     * @param recordtime the value for tcprecord.recordtime
     *
     * @mbg.generated
     */
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }
}