package com.ril.mapper;

import com.ril.bean.Machine;
import com.ril.bean.MachineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated
     */
    long countByExample(MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated
     */
    int deleteByExample(MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long machid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated
     */
    int insert(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated
     */
    int insertSelective(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated
     */
    List<Machine> selectByExample(MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated
     */
    Machine selectByPrimaryKey(Long machid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Machine record, @Param("example") MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Machine record, @Param("example") MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Machine record);
}