package com.ril.mapper;

import com.ril.bean.NOCRecord;
import com.ril.bean.NOCRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NOCRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nocrecord
     *
     * @mbg.generated
     */
    long countByExample(NOCRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nocrecord
     *
     * @mbg.generated
     */
    int deleteByExample(NOCRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nocrecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nocrecord
     *
     * @mbg.generated
     */
    int insert(NOCRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nocrecord
     *
     * @mbg.generated
     */
    int insertSelective(NOCRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nocrecord
     *
     * @mbg.generated
     */
    List<NOCRecord> selectByExample(NOCRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nocrecord
     *
     * @mbg.generated
     */
    NOCRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nocrecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NOCRecord record, @Param("example") NOCRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nocrecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NOCRecord record, @Param("example") NOCRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nocrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NOCRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nocrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NOCRecord record);
}