package com.ril.mapper;

import com.ril.bean.TCPRecord;
import com.ril.bean.TCPRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCPRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcprecord
     *
     * @mbg.generated
     */
    long countByExample(TCPRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcprecord
     *
     * @mbg.generated
     */
    int deleteByExample(TCPRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcprecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcprecord
     *
     * @mbg.generated
     */
    int insert(TCPRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcprecord
     *
     * @mbg.generated
     */
    int insertSelective(TCPRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcprecord
     *
     * @mbg.generated
     */
    List<TCPRecord> selectByExample(TCPRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcprecord
     *
     * @mbg.generated
     */
    TCPRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcprecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCPRecord record, @Param("example") TCPRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcprecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCPRecord record, @Param("example") TCPRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcprecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCPRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcprecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCPRecord record);
}